### ISSUE TITLE
Entities &quot; and &apos; are converted incorrectly.

### ISSUE THREAD

**Issue by ostomachion** [jfcardinal/HtmlToXml#4]
Both `&quot;` and `&apos;` are converted to decimal numeric entities, but with their hex values, resulting in characters that are not even allowed in XML. Both named entities are allowed in XML and should be used rather than the numeric entities.

**Comment by jfcardinal** [comment]
I discovered and fixed those two bugs earlier this month but hadn't pushed the changes up. I chose to correct the numeric entities, but given &amp;amp;, &amp;lt;, and &amp;gt; are converted to named entities, and " and ' represent the remaining two reserved characters in XML, using &amp;quot; and &amp;apos; is probably better.

EDIT: Fixed encoding of entities
