### ISSUE TITLE
Thanks! version of the framework 

### ISSUE THREAD

**Issue by boy8199** [jfcardinal/HtmlToXml#6]
This version of the framework is a bit high, it would be great if you used Framework 4.0

**Comment by jfcardinal** [comment]
The project was (mostly) developed in 2019 or earlier, and using .Net Standard 2.0 allowed the library to be used in Net Framework and other .NET versions, including .NET code. If I update it, I'll probably move forward, not back, and target .NET 5.

You should be able to use this code in your Framework 4.0 project already. If you can't, please explain why.
